src/Entity/Race.php
<?php

namespace App\Entity;

use App\Repository\RaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RaceRepository::class)]
class Race
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column]
    private ?int $bonus_force = null;

    #[ORM\Column]
    private ?int $bonus_agilite = null;

    #[ORM\Column]
    private ?int $bonus_endurance = null;

    #[ORM\OneToMany(mappedBy: 'race', targetEntity: Personnage::class)]
    private Collection $personnages;

    public function __construct()
    {
        $this->personnages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getBonusForce(): ?int
    {
        return $this->bonus_force;
    }

    public function setBonusForce(int $bonus_force): self
    {
        $this->bonus_force = $bonus_force;

        return $this;
    }

    public function getBonusAgilite(): ?int
    {
        return $this->bonus_agilite;
    }

    public function setBonusAgilite(int $bonus_agilite): self
    {
        $this->bonus_agilite = $bonus_agilite;

        return $this;
    }

    public function getBonusEndurance(): ?int
    {
        return $this->bonus_endurance;
    }

    public function setBonusEndurance(int $bonus_endurance): self
    {
        $this->bonus_endurance = $bonus_endurance;

        return $this;
    }

    /**
     * @return Collection<int, Personnage>
     */
    public function getPersonnages(): Collection
    {
        return $this->personnages;
    }

    public function addPersonnage(Personnage $personnage): self
    {
        if (!$this->personnages->contains($personnage)) {
            $this->personnages->add($personnage);
            $personnage->setRace($this);
        }

        return $this;
    }

    public function removePersonnage(Personnage $personnage): self
    {
        if ($this->personnages->removeElement($personnage)) {
            // set the owning side to null (unless already changed)
            if ($personnage->getRace() === $this) {
                $personnage->setRace(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->libelle; 
    }
}

src/Form/RaceType.php
<?php

namespace App\Form;

use App\Entity\Race;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('bonus_force')
            ->add('bonus_agilite')
            ->add('bonus_endurance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Race::class,
        ]);
    }
}

src/Controller/RaceController.php
<?php

namespace App\Controller;

use App\Entity\Race;
use App\Form\RaceType;
use App\Repository\RaceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/race')]
class RaceController extends AbstractController
{
    #[Route('/', name: 'app_race_index', methods: ['GET'])]
    public function index(RaceRepository $raceRepository): Response
    {
        return $this->render('race/index.html.twig', [
            'races' => $raceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_race_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RaceRepository $raceRepository): Response
    {
        $race = new Race();
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $raceRepository->save($race, true);

            return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('race/new.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_race_show', methods: ['GET'])]
    public function show(Race $race): Response
    {
        return $this->render('race/show.html.twig', [
            'race' => $race,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_race_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Race $race, RaceRepository $raceRepository): Response
    {
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $raceRepository->save($race, true);

            return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('race/edit.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_race_delete', methods: ['POST'])]
    public function delete(Request $request, Race $race, RaceRepository $raceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$race->getId(), $request->request->get('_token'))) {
            $raceRepository->remove($race, true);
        }

        return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/race/_delete_form.html.twig
<form method="post" action="{{ path('app_race_delete', {'id': race.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ race.id) }}">
    <button class="btn">Delete</button>
</form>

templates/race/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/race/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Race{% endblock %}

{% block body %}
    <h1>Edit Race</h1>

    {{ include('race/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_race_index') }}">back to list</a>

    {{ include('race/_delete_form.html.twig') }}
{% endblock %}

templates/race/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Race{% endblock %}

{% block body %}
<div class="fondBeige">
    <h1>Race</h1>

        {% for race in races %}
                <li><span>Id</span>{{ race.id }}</li>
                <li><span>Id</span>{{ race.libelle }}</li>
                <li><span>Id</span>{{ race.bonusForce }}</li>
                <li><span>Id</span>{{ race.bonusAgilite }}</li>
                <li><span>Id</span>{{ race.bonusEndurance }}</li>
                <li><span>Id</span>
                    <a href="{{ path('app_race_show', {'id': race.id}) }}">show</a>
                    <a href="{{ path('app_race_edit', {'id': race.id}) }}">edit</a>
                </li>

        {% else %}

                <p>no records found</p>

        {% endfor %}

    <a href="{{ path('app_race_new') }}">Create new</a>
    </div>
{% endblock %}

templates/race/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Race{% endblock %}

{% block body %}
<div class="fondBeige">
    <h1>Create new Race</h1>

    {{ include('race/_form.html.twig') }}

    <a href="{{ path('app_race_index') }}">back to list</a>
</div>
{% endblock %}

templates/race/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Race{% endblock %}

{% block body %}
    <h1>Race</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ race.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ race.libelle }}</td>
            </tr>
            <tr>
                <th>Bonus_force</th>
                <td>{{ race.bonusForce }}</td>
            </tr>
            <tr>
                <th>Bonus_agilite</th>
                <td>{{ race.bonusAgilite }}</td>
            </tr>
            <tr>
                <th>Bonus_endurance</th>
                <td>{{ race.bonusEndurance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_race_index') }}">back to list</a>

    <a href="{{ path('app_race_edit', {'id': race.id}) }}">edit</a>

    {{ include('race/_delete_form.html.twig') }}
{% endblock %}